apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: etcd
    k8s-app: etcd
    monitoring.openshift.io/scrape-profile: operational
  name: etcd-operational
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: ""
    interval: 30s
    metricRelabelings:
    - action: keep
      regex: (etcd_disk_backend_commit_duration_seconds_bucket|etcd_disk_wal_fsync_duration_seconds_bucket|etcd_mvcc_db_total_size_in_bytes|etcd_mvcc_db_total_size_in_use_in_bytes|etcd_network_peer_round_trip_time_seconds_bucket|etcd_network_peer_sent_failures_total|etcd_server_has_leader|etcd_server_is_leader|etcd_server_proposals_failed_total|etcd_server_quota_backend_bytes|grpc_server_handled_total|grpc_server_handling_seconds_bucket|grpc_server_started_total)
      sourceLabels:
      - __name__
    port: etcd-metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      insecureSkipVerify: false
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - openshift-etcd
  selector:
    matchLabels:
      k8s-app: etcd
